name: Install GitHub Cli
description: "Install GitHub Cli"
branding:
  icon: 'code'  
  color: 'gray-dark'
inputs:
  autoLogin: 
    default: true
    required: false
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
            && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y
          
          if "${{ inputs.autoLogin }}"; then
             gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          fi
